//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandmadeShop2.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authotization
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public int ID_role { get; set; }
        public int ID_user { get; set; }
        public int ID_aut { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Users Users { get; set; }
    }
}
