//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandmadeShop2.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mater_Product
    {
        public int ID_MP { get; set; }
        public int ID_product { get; set; }
        public int ID_mater { get; set; }
        public Nullable<int> Number_of_mater { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Product Product { get; set; }
    }
}
